server:
  port: 8080

spring:
  profiles:
    active: dev

io:
  fileUploadPath: webapps/images/avatar
  file-host: images/avatar
  bucket-app-id: "32791238237612378123"
  bucket-app-secret: "EF8WnIPlnDFYPEIt"
  minio:
    export-endpoint: "http://202.189.9.147:9000"
    endpoint: "http://202.189.9.147:9000"
    access-key: "admin"
    secret-key: "111111"
